In [2]:
#Numpy arrey
# create a numpy arrey:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# numpy Array indexing:
#Access Arrey Elements:
Arrey indexing is the same as accenssing an array element:


In [3]:
#EX
import numpy as np

arr = np.array([1,2,3,4])

print(arr[1])

2


In [ ]:
#Numpy Array Slicing
Slicing arrays
We pass slice instead of the index like this:[start:end]
we can also define the step ,like this this:[start:end:step]
if we dont pass start its considerd 0

In [4]:
#Ex
#slice elemets from index 1 to index 5 from the following array:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
#Numpy Data Types
*by default python have these data types
>strings - used to represent text data,the next is given under quote marks Eg."ABCD"
>integer - used o represent integer number eg.-1,-2,-3
>float - used to represent real numbers eg.1.2 ,2.3,6.2
>boolean - used to represent True or False
>complex - used to represent complex numbers eg.1.0+2.0j,1.5+2.5j    


In [6]:
#Ex,2
import numpy as np

arr = np.array([1,2,3,4])

print(arr.dtype)

int32


In [7]:
#Numpy Copy:
#Ex
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [8]:
#Numpy Array Shape
#print the shape of 2-D array:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

(2, 4)


In [ ]:
#Numpy Array Reshaping:
Reshaping means changing the shape of the array

In [9]:
#Ex
#convert the following 1-D array with 12 elements into a 2-D array:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Numpy Joining Array:
joining means putting contents of two or more arrays in a single array

In [10]:
#join two array:
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
#Numpy Spliting Array
spliting is reverse operation of joining

In [11]:
#Ex.
#split the array in 3 parts:
import numpy as np

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#Numpy Searching Arrays
an array for a certain value ,and return the indexes that get a match.

In [12]:
#Ex:
#find the indexes where the value is 4:
import numpy as np

arr = np.array([1,2,3,4,5,4,4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [ ]:
#Numpy Sorting Arrays:
sorting means putting elements in an ordered sequence

In [13]:
#Ex:
#sort the array:
import numpy as np

arr = np.array([3,2,0,1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
#Numpy Filter Array:
Getting some elements out of an existing array and creating a new array out of them is called filtering

In [14]:
#create an array from the elements on index 0 and 2:
import numpy as np

arr = np.array([41,42,43,44])

x = [True,False,True,False]

newarr = arr[x]

print(newarr)

[41 43]
